#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 07, 2018 02:29:39 AM IST  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join D:/ Projects(Master) gateway-master {Student Dashboard} change.png]} {user image} user {}}
        {{[file join D:/ Projects(Master) gateway-master {Student Dashboard} manufacturing.png]} {user image} user {}}
        {{[file join D:/ Projects(Master) gateway-master {Student Dashboard} studentpack.png]} {user image} user {}}
        {{[file join D:/ Projects(Master) gateway-master {Student Dashboard} vitamin-c.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #5b9ed8
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d8955b
set vTcl(analog_color_p) #5b5fd8
set vTcl(analog_color_m) #5bd8d4
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Product Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Product Sans} -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Product Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Product Sans} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Product Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#455a64} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1600x900+316+34
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1600 900
    wm minsize $top 1600 900
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Dashboard : Student"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Dashboard : Student} 
    vTcl:DefineAlias "$top.lab40" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but41 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#fff} \
        -highlightbackground {#5b9ed8} -highlightcolor black -pady 0 \
        -text Logout 
    vTcl:DefineAlias "$top.but41" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Logged in at : } 
    vTcl:DefineAlias "$top.lab42" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.lab43" "LogInTimeLabel" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text on 
    vTcl:DefineAlias "$top.lab44" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.lab45" "LogInDateLabel" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {My Account :} 
    vTcl:DefineAlias "$top.lab46" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.lab47" "StudNameLabel" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -background {#263238} -height 135 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 475 
    vTcl:DefineAlias "$top.fra48" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    button $site_3_0.but52 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -foreground {#fff} -highlightbackground {#5b9ed8} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ Projects(Master) gateway-master {Student Dashboard} change.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but52" "Button2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Price 
    vTcl:DefineAlias "$site_3_0.lab70" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab40" "PriceLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 20 -y 20 -width 76 -relwidth 0 -height 96 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 120 -y 30 -width 115 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 120 -y 70 -width 272 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra40 \
        -borderwidth 2 -background {#263238} -height 135 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1055 
    vTcl:DefineAlias "$top.fra40" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra40
    frame $site_3_0.fra41 \
        -borderwidth 2 -background {#263238} -height 625 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 455 
    vTcl:DefineAlias "$site_3_0.fra41" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#263238} -activeforeground black -anchor e \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Search 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex40 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground {#5b9ed8} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 564 -wrap word 
    .top39.fra40.tex40 configure -font TkTextFont
    .top39.fra40.tex40 insert end text
    vTcl:DefineAlias "$site_3_0.tex40" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but40 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -foreground {#fff} -highlightbackground {#5b9ed8} \
        -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$site_3_0.but40" "Button2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra41 \
        -in $site_3_0 -x 591 -y 268 -width 455 -height 625 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 90 -y 60 -width 115 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex40 \
        -in $site_3_0 -x 230 -y 60 -width 564 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but40 \
        -in $site_3_0 -x 820 -y 60 -width 86 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra42 \
        -borderwidth 2 -background {#263238} -height 495 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra42" "Frame1_3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra42
    label $site_3_0.lab45 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Uses 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#263238} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right 
    vTcl:DefineAlias "$site_3_0.lab57" "UsesLabelInfo_7" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 20 -width 65 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 60 -y 110 -width 225 -height 337 -anchor nw \
        -bordermode ignore 
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.lab48" "RegNoLabel" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra58 \
        -borderwidth 2 -background {#263238} -height 135 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 475 
    vTcl:DefineAlias "$top.fra58" "Frame1_11" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra58
    button $site_3_0.but52 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -foreground {#fff} -highlightbackground {#5b9ed8} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ Projects(Master) gateway-master {Student Dashboard} manufacturing.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but52" "Button2_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Manufacturer 
    vTcl:DefineAlias "$site_3_0.lab71" "Label2_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab41" "DrugLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 20 -y 20 -width 76 -relwidth 0 -height 96 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 120 -y 20 -width 155 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 120 -y 60 -width 272 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra61 \
        -borderwidth 2 -background {#263238} -height 165 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 475 
    vTcl:DefineAlias "$top.fra61" "Frame1_12" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra61
    button $site_3_0.but52 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -foreground {#fff} -highlightbackground {#5b9ed8} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ Projects(Master) gateway-master {Student Dashboard} studentpack.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but52" "Button2_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Pack 
    vTcl:DefineAlias "$site_3_0.lab72" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab43" "PackLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 20 -y 30 -width 76 -relwidth 0 -height 96 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 120 -y 30 -width 115 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 120 -y 70 -width 272 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra62 \
        -borderwidth 2 -background {#263238} -height 165 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 475 
    vTcl:DefineAlias "$top.fra62" "Frame1_4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra62
    button $site_3_0.but52 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -foreground {#fff} -highlightbackground {#5b9ed8} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ Projects(Master) gateway-master {Student Dashboard} vitamin-c.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but52" "Button2_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Constituent 
    vTcl:DefineAlias "$site_3_0.lab73" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab44" "ConstituentLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 20 -y 30 -width 76 -relwidth 0 -height 96 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 120 -y 30 -width 145 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 120 -y 70 -width 272 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra53 \
        -borderwidth 2 -background {#263238} -height 495 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 335 
    vTcl:DefineAlias "$top.fra53" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra53
    label $site_3_0.lab45 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text {Side Effects} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#263238} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right 
    vTcl:DefineAlias "$site_3_0.lab56" "UsesLabelInfo_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 20 -width 135 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 50 -y 110 -width 225 -height 337 -anchor nw \
        -bordermode ignore 
    frame $top.fra54 \
        -borderwidth 2 -background {#263238} -height 495 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra54" "Frame1_5" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra54
    label $site_3_0.lab45 \
        -activebackground {#263238} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Substitutes 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground {#263238} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right 
    vTcl:DefineAlias "$site_3_0.lab48" "UsesLabelInfo_4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 20 -width 135 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 60 -y 100 -width 225 -relwidth 0 -height 337 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab40 \
        -in $top -x 0 -y 0 -width 1601 -relwidth 0 -height 136 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but41 \
        -in $top -x 1480 -y 160 -width 89 -relwidth 0 -height 43 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 1040 -y 160 -width 115 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 1160 -y 160 -width 95 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 1260 -y 160 -width 45 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 1310 -y 160 -width 105 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 20 -y 160 -width 115 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 140 -y 160 -width 115 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.fra48 \
        -in $top -x 1100 -y 220 -width 475 -relwidth 0 -height 135 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra40 \
        -in $top -x 30 -y 220 -width 1055 -relwidth 0 -height 135 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra42 \
        -in $top -x 30 -y 370 -width 345 -relwidth 0 -height 495 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 270 -y 160 -width 115 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.fra58 \
        -in $top -x 1100 -y 370 -width 475 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.fra61 \
        -in $top -x 1100 -y 520 -width 475 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra62 \
        -in $top -x 1100 -y 700 -width 475 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 390 -y 370 -width 335 -relwidth 0 -height 495 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra54 \
        -in $top -x 740 -y 370 -width 345 -relwidth 0 -height 495 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

