# -*- coding: utf-8 -*-

"""
    healthoslib.controllers.food_controller

    This file was automatically generated by APIMATIC BETA v2.0 on 02/18/2017
"""

from .base_controller import BaseController
from ..api_helper import APIHelper
from ..configuration import Configuration
from ..http.auth.o_auth_2 import OAuth2

class FoodController(BaseController):

    """A Controller to access Endpoints in the healthoslib API."""
    

    def search_food_restaurants(self,
                                food_restaurant_query):
        """Does a GET request to /search/food/restaurants/{food_restaurant_query}.

        TODO: Add Description

        Args:
            food_restaurant_query (string): TODO: type description here.
                Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/search/food/restaurants/{food_restaurant_query}'
        _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, { 
            'food_restaurant_query': food_restaurant_query
        })
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def get_all_food_brands(self,
                            page,
                            size):
        """Does a GET request to /food/brands.

        TODO: Add Description

        Args:
            page (int): TODO: type description here. Example: 
            size (int): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/food/brands'
        _query_url = APIHelper.clean_url(_query_builder)
        _query_parameters = {
            'page': page,
            'size': size
        }

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers, query_parameters=_query_parameters)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def get_food_items_by_restaurant(self,
                                     page,
                                     size,
                                     food_restaurant_id):
        """Does a GET request to /food/restaurants/{food_restaurant_id}/items.

        TODO: Add Description

        Args:
            page (int): TODO: type description here. Example: 
            size (int): TODO: type description here. Example: 
            food_restaurant_id (string): TODO: type description here. Example:
                
        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/food/restaurants/{food_restaurant_id}/items'
        _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, { 
            'food_restaurant_id': food_restaurant_id
        })
        _query_url = APIHelper.clean_url(_query_builder)
        _query_parameters = {
            'page': page,
            'size': size
        }

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers, query_parameters=_query_parameters)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def search_food_brands(self,
                           food_brand_query):
        """Does a GET request to /search/food/brands/{food_brand_query}.

        TODO: Add Description

        Args:
            food_brand_query (string): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/search/food/brands/{food_brand_query}'
        _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, { 
            'food_brand_query': food_brand_query
        })
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def get_food_item(self,
                      food_item_id):
        """Does a GET request to /food/items/{food_item_id}.

        TODO: Add Description

        Args:
            food_item_id (string): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/food/items/{food_item_id}'
        _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, { 
            'food_item_id': food_item_id
        })
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def get_all_food_items(self,
                           page,
                           size):
        """Does a GET request to /food/items.

        TODO: Add Description

        Args:
            page (int): TODO: type description here. Example: 
            size (int): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/food/items'
        _query_url = APIHelper.clean_url(_query_builder)
        _query_parameters = {
            'page': page,
            'size': size
        }

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers, query_parameters=_query_parameters)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def search_food_items(self,
                          food_item_query):
        """Does a GET request to /search/food/items/{food_item_query}.

        TODO: Add Description

        Args:
            food_item_query (string): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/search/food/items/{food_item_query}'
        _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, { 
            'food_item_query': food_item_query
        })
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def get_all_food_restaurants(self,
                                 page,
                                 size):
        """Does a GET request to /food/restaurants.

        TODO: Add Description

        Args:
            page (int): TODO: type description here. Example: 
            size (int): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/food/restaurants'
        _query_url = APIHelper.clean_url(_query_builder)
        _query_parameters = {
            'page': page,
            'size': size
        }

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers, query_parameters=_query_parameters)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)

    def get_food_items_by_brand(self,
                                page,
                                size,
                                food_brand_id):
        """Does a GET request to /food/brands/{food_brand_id}/items.

        TODO: Add Description

        Args:
            page (int): TODO: type description here. Example: 
            size (int): TODO: type description here. Example: 
            food_brand_id (string): TODO: type description here. Example: 

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri.format(Configuration.host)
        _query_builder += '/food/brands/{food_brand_id}/items'
        _query_builder = APIHelper.append_url_with_template_parameters(_query_builder, { 
            'food_brand_id': food_brand_id
        })
        _query_url = APIHelper.clean_url(_query_builder)
        _query_parameters = {
            'page': page,
            'size': size
        }

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers, query_parameters=_query_parameters)
        OAuth2.apply(_request)
        _context = self.execute_request(_request)        
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body)
