#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 07, 2018 11:56:29 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #5b9ed8
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d8955b
set vTcl(analog_color_p) #5b5fd8
set vTcl(analog_color_m) #5bd8d4
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Product Sans} -size 24 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Product Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Product Sans} -size 16 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Product Sans} -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {Product Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#455a64} 
    wm focusmodel $top passive
    wm geometry $top 1600x900+110+62
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 16 1055
    wm minsize $top 1600 900
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Student Services : Diseases"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab40 \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -text {Diseases & Lab Tests} 
    vTcl:DefineAlias "$top.lab40" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -text {My Account :} 
    vTcl:DefineAlias "$top.lab41" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Ritwik Badola} 
    vTcl:DefineAlias "$top.lab42" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 17BCE7140 
    vTcl:DefineAlias "$top.lab43" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Logged in at :} 
    vTcl:DefineAlias "$top.lab44" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 23:25:29 
    vTcl:DefineAlias "$top.lab45" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text on 
    vTcl:DefineAlias "$top.lab46" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 07/10/2018 
    vTcl:DefineAlias "$top.lab47" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -relief raised -background {#263238} -height 85 \
        -width 515 
    vTcl:DefineAlias "$top.fra48" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab50 \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -text Search 
    vTcl:DefineAlias "$site_3_0.lab50" "Label4" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex51 \
        -background white -font font9 -foreground black -height 34 \
        -highlightbackground {#5b9ed8} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top39.fra48.tex51 configure -font font9
    .top39.fra48.tex51 insert end text
    vTcl:DefineAlias "$site_3_0.tex51" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#fff} \
        -highlightbackground {#5b9ed8} -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$site_3_0.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 20 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.tex51 \
        -in $site_3_0 -x 110 -y 30 -width 314 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 450 -y 30 -anchor nw -bordermode ignore 
    label $top.lab49 \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#fff} \
        -text Diseases 
    vTcl:DefineAlias "$top.lab49" "Label3" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra53 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -width 515 
    vTcl:DefineAlias "$top.fra53" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra53
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Name :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -anchor w -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab73" "Label5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 100 -y 20 -width 395 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra54 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 515 
    vTcl:DefineAlias "$top.fra54" "Frame2_7" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra54
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Category :} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label4_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab74" "Label5_13" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab56 \
        -in $site_3_0 -x 20 -y 20 -width 100 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 150 -y 20 -width 325 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra57 \
        -borderwidth 2 -relief groove -background {#263238} -height 275 \
        -width 515 
    vTcl:DefineAlias "$top.fra57" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra57
    label $site_3_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {More Information} 
    vTcl:DefineAlias "$site_3_0.lab58" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab75" "Label5_14" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab58 \
        -in $site_3_0 -x 20 -y 20 -width 160 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 20 -y 70 -width 455 -relwidth 0 -height 177 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::separator $top.tSe59 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe59" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Lab Tests} 
    vTcl:DefineAlias "$top.lab60" "Label3_11" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra61 \
        -borderwidth 2 -relief raised -background {#263238} -height 85 \
        -width 945 
    vTcl:DefineAlias "$top.fra61" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra61
    label $site_3_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Search 
    vTcl:DefineAlias "$site_3_0.lab62" "Label4_12" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex63 \
        -background white -font font9 -foreground black -height 34 \
        -highlightbackground {#5b9ed8} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 724 -wrap word 
    .top39.fra61.tex63 configure -font font9
    .top39.fra61.tex63 insert end text
    vTcl:DefineAlias "$site_3_0.tex63" "Text1_13" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but64 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#fff} \
        -highlightbackground {#5b9ed8} -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$site_3_0.but64" "Button1_14" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab62 \
        -in $site_3_0 -x 30 -y 30 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex63 \
        -in $site_3_0 -x 130 -y 30 -width 724 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 880 -y 30 -width 39 -height 35 -anchor nw \
        -bordermode ignore 
    frame $top.fra65 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 545 
    vTcl:DefineAlias "$top.fra65" "Frame2_15" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra65
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Name :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab76" "Label5_15" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 110 -y 20 -width 395 -height 27 -anchor nw \
        -bordermode ignore 
    frame $top.fra66 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 395 
    vTcl:DefineAlias "$top.fra66" "Frame2_10" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra66
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Test Code :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab77" "Label5_16" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 110 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 150 -y 20 -width 215 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra67 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 545 
    vTcl:DefineAlias "$top.fra67" "Frame2_11" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra67
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Alternate Name :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab79" "Label5_17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 160 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 200 -y 20 -width 315 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra68 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 395 
    vTcl:DefineAlias "$top.fra68" "Frame2_11" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra68
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Frequency :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab78" "Label5_17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 110 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 150 -y 20 -width 215 -height 27 -anchor nw \
        -bordermode ignore 
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background {#263238} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 955 
    vTcl:DefineAlias "$top.fra69" "Frame2_12" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra69
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Laboratory :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab80" "Label5_17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 120 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 166 -y 21 -width 765 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra71 \
        -borderwidth 2 -relief groove -background {#263238} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 475 
    vTcl:DefineAlias "$top.fra71" "Frame2_12" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra71
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Specimen Types :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab81" "Label5_17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 160 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 30 -y 70 -width 415 -relwidth 0 -height 97 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra72 \
        -borderwidth 2 -relief groove -background {#263238} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 465 
    vTcl:DefineAlias "$top.fra72" "Frame2_13" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra72
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Minimum Adult Volume :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab83" "Label5_17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 20 -width 230 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 31 -y 82 -width 395 -relwidth 0 -height 77 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab40 \
        -in $top -x 0 -y 0 -width 1604 -relwidth 0 -height 156 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 30 -y 180 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 150 -y 180 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab43 \
        -in $top -x 370 -y 180 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab44 \
        -in $top -x 30 -y 860 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab45 \
        -in $top -x 150 -y 860 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 250 -y 860 -width 33 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 300 -y 860 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.fra48 \
        -in $top -x 30 -y 310 -width 515 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 230 -y 260 -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 30 -y 410 -width 515 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra54 \
        -in $top -x 30 -y 490 -width 515 -height 65 -anchor nw \
        -bordermode ignore 
    place $top.fra57 \
        -in $top -x 30 -y 570 -width 515 -relwidth 0 -height 275 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe59 \
        -in $top -x 590 -y 270 -height 580 -anchor nw -bordermode inside 
    place $top.lab60 \
        -in $top -x 1010 -y 260 -width 125 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra61 \
        -in $top -x 620 -y 310 -width 945 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra65 \
        -in $top -x 620 -y 410 -width 545 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra66 \
        -in $top -x 1180 -y 410 -width 395 -relwidth 0 -height 65 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra67 \
        -in $top -x 620 -y 490 -width 545 -height 65 -anchor nw \
        -bordermode ignore 
    place $top.fra68 \
        -in $top -x 1180 -y 490 -width 395 -height 65 -anchor nw \
        -bordermode ignore 
    place $top.fra69 \
        -in $top -x 620 -y 570 -width 955 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra71 \
        -in $top -x 620 -y 650 -width 475 -relwidth 0 -height 195 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra72 \
        -in $top -x 1110 -y 650 -width 465 -height 195 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

