#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 07, 2018 09:18:31 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #5b9ed8
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d8955b
set vTcl(analog_color_p) #5b5fd8
set vTcl(analog_color_m) #5bd8d4
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Product Sans} -size 24 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Product Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Product Sans} -size 16 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Product Sans} -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {Product Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#455a64} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1600x900+77+31
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1600 1055
    wm minsize $top 1600 900
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Student Services : Food & Exercise"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Food & Exercise} 
    vTcl:DefineAlias "$top.lab40" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {My Account :} 
    vTcl:DefineAlias "$top.lab41" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Priyam Sahoo} 
    vTcl:DefineAlias "$top.lab42" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 17BCN7020 
    vTcl:DefineAlias "$top.lab43" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Logged in at :} 
    vTcl:DefineAlias "$top.lab44" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 19:59:45 
    vTcl:DefineAlias "$top.lab45" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text on 
    vTcl:DefineAlias "$top.lab46" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 07/10/2018 
    vTcl:DefineAlias "$top.lab47" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -relief raised -background {#455a64} -height 585 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 705 
    vTcl:DefineAlias "$top.fra48" "foodframe" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    frame $site_3_0.fra56 \
        -borderwidth 2 -relief raised -background {#263238} -height 85 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 645 
    vTcl:DefineAlias "$site_3_0.fra56" "Searchframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra56
    label $site_4_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Search 
    vTcl:DefineAlias "$site_4_0.lab58" "Label9" vTcl:WidgetProc "Toplevel1" 1
    text $site_4_0.tex59 \
        -background white -font font9 -foreground black -height 34 \
        -highlightbackground {#5b9ed8} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 434 -wrap word 
    .top39.fra48.fra56.tex59 configure -font font9
    .top39.fra48.fra56.tex59 insert end text
    vTcl:DefineAlias "$site_4_0.tex59" "Text2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but60 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#fff} \
        -highlightbackground {#5b9ed8} -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$site_4_0.but60" "Button4" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab58 \
        -in $site_4_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.tex59 \
        -in $site_4_0 -x 110 -y 30 -width 434 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but60 \
        -in $site_4_0 -x 570 -y 30 -width 39 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Food 
    vTcl:DefineAlias "$site_3_0.lab57" "FoodHeading" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra61 \
        -borderwidth 2 -relief groove -background {#263238} -height 365 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 645 
    vTcl:DefineAlias "$site_3_0.fra61" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra61
    label $site_4_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab62" "Label10" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab62 \
        -in $site_4_0 -x 30 -y 30 -width 582 -relwidth 0 -height 296 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra56 \
        -in $site_3_0 -x 30 -y 90 -width 645 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 320 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.fra61 \
        -in $site_3_0 -x 30 -y 190 -width 645 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra55 \
        -borderwidth 2 -relief raised -background {#455a64} -height 585 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 705 
    vTcl:DefineAlias "$top.fra55" "exerciseframe" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra55
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#455a64} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Exercise 
    vTcl:DefineAlias "$site_3_0.lab63" "Label7_6" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra40 \
        -borderwidth 2 -relief raised -background {#263238} -height 85 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 645 
    vTcl:DefineAlias "$site_3_0.fra40" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra40
    label $site_4_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Search 
    vTcl:DefineAlias "$site_4_0.lab41" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but43 \
        -activebackground {#263238} -activeforeground {#000000} \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#fff} \
        -highlightbackground {#5b9ed8} -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$site_4_0.but43" "Button4_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab41 \
        -in $site_4_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but43 \
        -in $site_4_0 -x 570 -y 30 -width 39 -height 35 -anchor nw \
        -bordermode ignore 
    text $site_3_0.tex42 \
        -background white -font font9 -foreground black -height 34 \
        -highlightbackground {#5b9ed8} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 434 -wrap word 
    .top39.fra55.tex42 configure -font font9
    .top39.fra55.tex42 insert end text
    vTcl:DefineAlias "$site_3_0.tex42" "Text1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra44 \
        -borderwidth 2 -relief groove -background {#263238} -height 365 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 645 
    vTcl:DefineAlias "$site_3_0.fra44" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra44
    label $site_4_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#263238} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab45" "Label10_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab45 \
        -in $site_4_0 -x 30 -y 30 -width 582 -relwidth 0 -height 296 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 300 -y 30 -width 109 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra40 \
        -in $site_3_0 -x 30 -y 90 -width 645 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex42 \
        -in $site_3_0 -x 140 -y 120 -width 434 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra44 \
        -in $site_3_0 -x 30 -y 190 -width 645 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab40 \
        -in $top -x 0 -y 0 -width 1602 -relwidth 0 -height 156 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 60 -y 190 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 180 -y 190 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab43 \
        -in $top -x 440 -y 190 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab44 \
        -in $top -x 60 -y 860 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab45 \
        -in $top -x 180 -y 860 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 310 -y 860 -width 43 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 370 -y 860 -width 103 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.fra48 \
        -in $top -x 60 -y 250 -width 705 -relwidth 0 -height 585 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra55 \
        -in $top -x 830 -y 250 -width 705 -relwidth 0 -height 585 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

