# -*- coding: utf-8 -*-

"""
    healthoslib.models.all_food_brands_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.base_model

class AllFoodBrandsResponse(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'All Food BrandsResponse' model.

    TODO: type model description here.

    Attributes:
        brand_name (string): TODO: type description here.
        food_brand_id (string): TODO: type description here.

    """

    def __init__(self, 
                 brand_name = None,
                 food_brand_id = None):
        """Constructor for the AllFoodBrandsResponse class"""
        
        # Initialize members of the class
        self.brand_name = brand_name
        self.food_brand_id = food_brand_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "brand_name" : "brand_name",
            "food_brand_id" : "food_brand_id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            brand_name = dictionary.get("brand_name")
            food_brand_id = dictionary.get("food_brand_id")
            # Return an object of this model
            return cls(brand_name,
                       food_brand_id)


