# -*- coding: utf-8 -*-

"""
    healthoslib.models.all_food_restaurants_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.base_model

class AllFoodRestaurantsResponse(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'All Food RestaurantsResponse' model.

    TODO: type model description here.

    Attributes:
        restaurant_name (string): TODO: type description here.
        food_restaurant_id (string): TODO: type description here.

    """

    def __init__(self, 
                 restaurant_name = None,
                 food_restaurant_id = None):
        """Constructor for the AllFoodRestaurantsResponse class"""
        
        # Initialize members of the class
        self.restaurant_name = restaurant_name
        self.food_restaurant_id = food_restaurant_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "restaurant_name" : "restaurant_name",
            "food_restaurant_id" : "food_restaurant_id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            restaurant_name = dictionary.get("restaurant_name")
            food_restaurant_id = dictionary.get("food_restaurant_id")
            # Return an object of this model
            return cls(restaurant_name,
                       food_restaurant_id)


