# -*- coding: utf-8 -*-

"""
    healthoslib.models.all_lab_tests_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.lab_test_data_34
import healthoslib.models.base_model

class AllLabTestsResponse(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'All Lab TestsResponse' model.

    TODO: type model description here.

    Attributes:
        lab_test_name (string): TODO: type description here.
        alternate_name (string): TODO: type description here.
        lab_test_id (string): TODO: type description here.
        lab_test_data (LabTestData34): TODO: type description here.

    """

    def __init__(self, 
                 lab_test_name = None,
                 alternate_name = None,
                 lab_test_id = None,
                 lab_test_data = None):
        """Constructor for the AllLabTestsResponse class"""
        
        # Initialize members of the class
        self.lab_test_name = lab_test_name
        self.alternate_name = alternate_name
        self.lab_test_id = lab_test_id
        self.lab_test_data = lab_test_data

        # Create a mapping from Model property names to API property names
        self.names = {
            "lab_test_name" : "lab_test_name",
            "alternate_name" : "alternate_name",
            "lab_test_id" : "lab_test_id",
            "lab_test_data" : "lab_test_data",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            lab_test_name = dictionary.get("lab_test_name")
            alternate_name = dictionary.get("alternate_name")
            lab_test_id = dictionary.get("lab_test_id")
            lab_test_data = healthoslib.models.lab_test_data_34.LabTestData34.from_dictionary(dictionary.get("lab_test_data")) if dictionary.get("lab_test_data") else None
            # Return an object of this model
            return cls(lab_test_name,
                       alternate_name,
                       lab_test_id,
                       lab_test_data)


