# -*- coding: utf-8 -*-

"""
    healthoslib.models.food_items_by_restaurant_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.base_model

class FoodItemsByRestaurantResponse(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'Food Items by RestaurantResponse' model.

    TODO: type model description here.

    Attributes:
        item_name (string): TODO: type description here.
        calories (int): TODO: type description here.
        serving_qty (float): TODO: type description here.
        serving_unit (string): TODO: type description here.
        food_item_id (string): TODO: type description here.
        food_brand_id (string): TODO: type description here.

    """

    def __init__(self, 
                 item_name = None,
                 calories = None,
                 serving_qty = None,
                 serving_unit = None,
                 food_item_id = None,
                 food_brand_id = None):
        """Constructor for the FoodItemsByRestaurantResponse class"""
        
        # Initialize members of the class
        self.item_name = item_name
        self.calories = calories
        self.serving_qty = serving_qty
        self.serving_unit = serving_unit
        self.food_item_id = food_item_id
        self.food_brand_id = food_brand_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "item_name" : "item_name",
            "calories" : "calories",
            "serving_qty" : "serving_qty",
            "serving_unit" : "serving_unit",
            "food_item_id" : "food_item_id",
            "food_brand_id" : "food_brand_id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            item_name = dictionary.get("item_name")
            calories = dictionary.get("calories")
            serving_qty = dictionary.get("serving_qty")
            serving_unit = dictionary.get("serving_unit")
            food_item_id = dictionary.get("food_item_id")
            food_brand_id = dictionary.get("food_brand_id")
            # Return an object of this model
            return cls(item_name,
                       calories,
                       serving_qty,
                       serving_unit,
                       food_item_id,
                       food_brand_id)


