# -*- coding: utf-8 -*-

"""
    healthoslib.models.item
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.base_model

class Item(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'Item' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.

    """

    def __init__(self, 
                 name = None):
        """Constructor for the Item class"""
        
        # Initialize members of the class
        self.name = name

        # Create a mapping from Model property names to API property names
        self.names = {
            "name" : "name",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            name = dictionary.get("name")
            # Return an object of this model
            return cls(name)


