# -*- coding: utf-8 -*-

"""
    healthoslib.models.popular_usage_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.usage
import healthoslib.models.base_model

class PopularUsageResponse(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'Popular UsageResponse' model.

    TODO: type model description here.

    Attributes:
        generic (string): TODO: type description here.
        usages (list of Usage): TODO: type description here.

    """

    def __init__(self, 
                 generic = None,
                 usages = None):
        """Constructor for the PopularUsageResponse class"""
        
        # Initialize members of the class
        self.generic = generic
        self.usages = usages

        # Create a mapping from Model property names to API property names
        self.names = {
            "generic" : "generic",
            "usages" : "usages",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            generic = dictionary.get("generic")
            usages = None
            if dictionary.get("usages") != None:
                usages = list()
                for structure in dictionary.get("usages"):
                    usages.append(healthoslib.models.usage.Usage.from_dictionary(structure))
            # Return an object of this model
            return cls(generic,
                       usages)


