# -*- coding: utf-8 -*-

"""
    healthoslib.models.schedule
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.base_model

class Schedule(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'Schedule' model.

    TODO: type model description here.

    Attributes:
        category (string): TODO: type description here.
        label (string): TODO: type description here.

    """

    def __init__(self, 
                 category = None,
                 label = None):
        """Constructor for the Schedule class"""
        
        # Initialize members of the class
        self.category = category
        self.label = label

        # Create a mapping from Model property names to API property names
        self.names = {
            "category" : "category",
            "label" : "label",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            category = dictionary.get("category")
            label = dictionary.get("label")
            # Return an object of this model
            return cls(category,
                       label)


