# -*- coding: utf-8 -*-

"""
    healthoslib.models.search_manufacturers_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
"""
import healthoslib.models.base_model

class SearchManufacturersResponse(healthoslib.models.base_model.BaseModel):

    """Implementation of the 'Search ManufacturersResponse' model.

    TODO: type model description here.

    Attributes:
        manufacturer_id (int): TODO: type description here.
        name (string): TODO: type description here.

    """

    def __init__(self, 
                 manufacturer_id = None,
                 name = None):
        """Constructor for the SearchManufacturersResponse class"""
        
        # Initialize members of the class
        self.manufacturer_id = manufacturer_id
        self.name = name

        # Create a mapping from Model property names to API property names
        self.names = {
            "manufacturer_id" : "manufacturer_id",
            "name" : "name",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            manufacturer_id = dictionary.get("manufacturer_id")
            name = dictionary.get("name")
            # Return an object of this model
            return cls(manufacturer_id,
                       name)


